language: ruby
rvm:
  - 1.9.3

env:
  - IP=127.0.0.1 PORT=4020 VERBOSE=false

install: true

before_script:
  - gem install pastebin
  - ./scripts/run_sc_server_master.sh
  - sleep 5 # give sc-server some time to start

script: phantomjs tests/phantomjs_runner.phantomjs

after_script: echo "Sharing failures summaries on pastebin for 1 hour..."; for f in *.html ; do test -e $f && ( id=`basename $f .html`; echo -n "   ${id} : "; pastebin -f "$f" -e '1H' ) ; done
