language: node_js
node_js:
  - "0.12"

before_script:
  #- ./scripts/run_sc_server_master.sh
  - ./scripts/run_bt_server_master.sh
  - sleep 15 # give sc-server some time to start

script: phantomjs phantomjs/test_runner_bt.js --no-experimental --exclude-targets=/sproutcore/greenhouse

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/92ce5eab32d974c44c69
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
